url: http://opencosmics.github.io
baseurl: ""

# Site settings
title: Open Cosmics
description: "A meta-project to establish a foundation for data storage and analysis for existing and new projects involving cosmic rays."

# Team names, titles and social links
people:
- name: Person One
  pic: 1
  position: Fancy Title
  social:
    - title: twitter
      url: #
    - title: github
      url: #

- name: Person Two
  pic: 2
  position: Fancier Title
  social:
    - title: twitter
      url: #
    - title: github
      url: #

- name: Person Three
  pic: 3
  position: Fanciest Title
  social:
    - title: twitter
      url: #
    - title: github
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/opencosmics
  - title: github
    url: https://github.com/opencosmics

# Build settings
markdown: kramdown
permalink: pretty
